version: "3.10"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/health_seeker
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      ENABLE_BACKGROUND_WORKERS: "true"
      ENABLE_EVENT_SUBSCRIBERS: "true"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app

  worker:
    build: .
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=info --queues=appointments
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/health_seeker
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      ENABLE_BACKGROUND_WORKERS: "true"
      ENABLE_EVENT_SUBSCRIBERS: "true"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health_seeker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
